version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: haske_db
      POSTGRES_USER: haske_user
      POSTGRES_PASSWORD: Haske2024

  web:
    build: .
    command: gunicorn haske_pro.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://haske_user:Haske2024@db:5432/haske_db